# Generated by Django 2.1.3 on 2018-12-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181207_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('looser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeats', to='projects.Animal')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victories', to='projects.Animal')),
            ],
        ),
    ]
