# Generated by Django 2.1.3 on 2018-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='summary',
            field=models.TextField(),
        ),
    ]
