# Generated by Django 2.1.3 on 2018-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=None, to='comments.Comment'),
        ),
    ]
