# Generated by Django 2.1.3 on 2018-12-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=100)),
                ('ar', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Numeric', 'Numeric'), ('AlphaNumeric', 'AlphaNumeric'), ('Boolean', 'Boolean'), ('Date', 'Date'), ('Button/Link', 'Button/Link')], max_length=100)),
                ('unique', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional'), ('Conditional', 'Conditional')], max_length=100)),
                ('validations', models.TextField(null=True)),
                ('Comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LinkTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reverse_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsecaseActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
                ('type', models.CharField(choices=[('Human', 'Human'), ('System', 'System')], max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='Datamodel',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
                ('message_en', models.TextField()),
                ('message_ar', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requirements.MessageType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
                ('desc', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.RequirementType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='requirements.Artifact')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('requirements.artifact',),
        ),
        migrations.AddField(
            model_name='link',
            name='linkType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='requirements.LinkTypes'),
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.ForeignKey(on_delete=None, related_name='soruce_links', to='requirements.Artifact'),
        ),
        migrations.AddField(
            model_name='link',
            name='target',
            field=models.ForeignKey(on_delete=None, related_name='targets', to='requirements.Artifact'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_requirements.artifact_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='usecaseactors',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecases', to='requirements.Actor'),
        ),
        migrations.AddField(
            model_name='usecaseactors',
            name='usecases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='requirements.Usecase'),
        ),
        migrations.AddField(
            model_name='field',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requirements.Datamodel'),
        ),
    ]
