# Generated by Django 2.1.3 on 2018-12-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryPoint', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('Normal', 'Normal'), ('Alternate', 'Alternate'), ('Exception', 'Exception')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNo', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('uses', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='requirements.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='usecase',
            name='businessRules',
            field=models.ManyToManyField(to='requirements.BusinessRule'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='usecase',
            name='extendes',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, related_name='included_by', to='requirements.Usecase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='includes',
            field=models.ForeignKey(blank=True, default=1, on_delete=None, related_name='extended_by', to='requirements.Usecase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecase',
            name='postConditions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='usecase',
            name='preConditions',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='usecase',
            name='requirements',
            field=models.ManyToManyField(to='requirements.Requirement'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='trigger',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='scenario',
            name='usecase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='requirements.Usecase'),
        ),
    ]
