# Generated by Django 2.1.3 on 2018-12-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_auto_20181224_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='businessRules',
            field=models.ManyToManyField(blank=True, to='requirements.BusinessRule'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='requirements.Requirement'),
        ),
    ]
