# Generated by Django 2.1.3 on 2018-12-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_auto_20181224_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='entryPoint',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
